INSERT INTO categories (key, name) VALUES
  ('tone_laser', '톤 개선 레이저'),
  ('fractional', '흉터/재생 레이저'),
  ('hair_removal', '제모 레이저'),
  ('vascular', '홍조 레이저'),
  ('acne_laser', '여드름 레이저'),
  ('genesis', '순한 톤/결 레이저'),
  ('rf_lifting', '고주파 리프팅'),
  ('inmode', '인모드'),
  ('needle_rf', '미세바늘 고주파'),
  ('hifu', '초음파 리프팅'),
  ('microwave', '윤곽/지방 리프팅'),
  ('hydra', '수분 스킨부스터'),
  ('regen', '재생 스킨부스터'),
  ('barrier', 'ECM 스킨부스터'),
  ('collagen', '콜라겐 부스터'),
  ('botox', '보톡스'),
  ('filler', '필러'),
  ('soothing', '진정/회복 관리');
